# Generated by Django 3.2.15 on 2023-07-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, verbose_name='设备名')),
            ],
            options={
                'verbose_name': '设备清单',
                'verbose_name_plural': '设备清单',
            },
        ),
        migrations.CreateModel(
            name='DeviceRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_repair_person', models.CharField(max_length=6, verbose_name='报修人')),
                ('repair_person', models.CharField(max_length=6, verbose_name='维修人')),
                ('repair_time', models.DateTimeField(auto_now_add=True, verbose_name='维修时间')),
                ('description_problem', models.CharField(max_length=200, verbose_name='故障描述')),
                ('repair_status', models.BooleanField(default=False, verbose_name='修复状态')),
                ('report_repair_category', models.SmallIntegerField(choices=[(1, '电气问题'), (2, '设备问题'), (3, '网络问题')], verbose_name='报修类别')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicerepair.devicedetail', verbose_name='设备名')),
            ],
        ),
    ]
